import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { Inter_Tight } from 'next/font/google';
import localFont from 'next/font/local';
import '@/app-fsd/styles/index.css';

const interTight = Inter_Tight({
  subsets: ['cyrillic'],
  variable: '--font-inter-tight',
  weight: ['400', '500', '600', '700', '800', '900']
});

const helvetiaNeue = localFont({
  src: '/fonts/HelveticaNeue-Roman.otf',
  variable: '--font-helvetica-neue'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${interTight.variable} ${helvetiaNeue.variable} antialiased`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
